// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	// 注册
	Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*CommonRsp, error)
	// 登录
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*CommonRsp, error)
	// 查询用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.name, "User.Register", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoRsp, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(GetUserInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	// 注册
	Register(context.Context, *RegisterReq, *CommonRsp) error
	// 登录
	Login(context.Context, *LoginReq, *CommonRsp) error
	// 查询用户信息
	GetUserInfo(context.Context, *GetUserInfoReq, *GetUserInfoRsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Register(ctx context.Context, in *RegisterReq, out *CommonRsp) error
		Login(ctx context.Context, in *LoginReq, out *CommonRsp) error
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, out *GetUserInfoRsp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Register(ctx context.Context, in *RegisterReq, out *CommonRsp) error {
	return h.UserHandler.Register(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *LoginReq, out *CommonRsp) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *GetUserInfoReq, out *GetUserInfoRsp) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}
